import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navigation from "@/app/components/Navigation";

const robotoCondensed = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensed.className} antialiased max-w-7xl mx-auto mt-8`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
